//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.11
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class pixy {
  public static int pixy_init() {
    int ret = pixyPINVOKE.pixy_init();
    return ret;
  }

  public static int pixy_get_blocks(ushort max_blocks, BlockArray blocks) {
    int ret = pixyPINVOKE.pixy_get_blocks(max_blocks, BlockArray.getCPtr(blocks));
    return ret;
  }

  public static void pixy_close() {
    pixyPINVOKE.pixy_close();
  }

}
